<?php
namespace Database\Seeders;
use App\Models\Content;
use Illuminate\Database\Seeder;
class DatabaseSeeder extends Seeder {
    public function run(): void {
        $put=function(string $kind,string $slug,string $title,array $extra=[]) { return Content::firstOrCreate(['kind'=>$kind,'slug'=>$slug],array_merge(['title'=>$title,'is_published'=>true,'position'=>0],$extra)); };
        $put('banners','perjalanan-ukpr','Ilmu yang menginspirasi. Karakter yang berarti.',['subtitle'=>'UNIVERSITAS KRISTEN PALANGKA RAYA','summary'=>'Temukan ruang untuk belajar, bertumbuh, dan memberi arti. Mulai perjalanan pendidikanmu bersama UKPR.','body'=>'Kegiatan mahasiswa Universitas Kristen Palangka Raya','link'=>'/pmb','image_path'=>is_file(storage_path('app/private/media/campus.webp'))?'media/campus.webp':null]);
        $put('pages','beranda','Pendidikan yang bermakna. Kontribusi yang nyata.',['summary'=>'Sejak 1987, UKPR hadir sebagai perguruan tinggi milik GKE yang berlandaskan nilai Kristiani.','body'=>'Terbuka bagi putra-putri bangsa, UKPR menghubungkan pendidikan dengan pembentukan karakter dan kontribusi bagi masyarakat.']);
        $put('pages','profil','Mengenal UKPR',['summary'=>'Pendidikan tinggi dengan landasan nilai Kristiani di Palangka Raya, Kalimantan Tengah.','body'=>"## Ilmu, iman, dan integritas\nUKPR merupakan perguruan tinggi milik GKE. Kampus ini membuka kesempatan pendidikan bagi putra-putri bangsa dan menempatkan pengetahuan serta karakter sebagai bagian dari perjalanan belajar.\n\n## Berakar di Kalimantan Tengah\nUKPR menjadi ruang bagi mahasiswa untuk mengembangkan diri dan berkontribusi bagi masyarakat.\n\nProfil kelembagaan lengkap akan dilengkapi oleh pengelola kampus."]);
        $put('pages','sejarah','Perjalanan sejak 1987',['summary'=>'UKPR telah berdiri sejak tahun 1987.','body'=>"## Awal perjalanan\nTahun berdiri UKPR tercantum dalam pengumuman resmi PMB 2026/2027.\n\nKronologi pendirian, perubahan kelembagaan, dan tonggak perkembangan akan dilengkapi oleh pengelola kampus berdasarkan dokumen resmi."]);
        $put('pages','visi-misi','Visi & misi',['summary'=>'Arah pengembangan Universitas Kristen Palangka Raya.','body'=>'Rumusan visi dan misi resmi akan dilengkapi oleh pengelola kampus berdasarkan dokumen kelembagaan yang berlaku.']);
        $put('pages','pmb','Mulai perjalananmu di UKPR',['subtitle'=>'PENERIMAAN MAHASISWA BARU 2026/2027','summary'=>'Kenali pilihan studi, siapkan persyaratan, dan ikuti pendaftaran mahasiswa baru.','body'=>"## Jadwal pendaftaran\n- Gelombang I: Januari–Juli 2026\n- Gelombang II: Agustus–November 2026\n\n## Siapkan dokumen\nIsi formulir daring dan siapkan hasil pindai KTP, Kartu Keluarga, ijazah atau surat keterangan lulus, serta foto berwarna ukuran 4×6. Informasi dokumen bagi calon mahasiswa yang belum lulus perlu dikonfirmasi kepada panitia.\n\n## Hubungi panitia\n- Frid Agustinus: 0852-4953-2732\n- Guslyani: 0813-4795-5336\n- Deby: 0813-8279-1912\n- Feter: 0856-5409-7162\n- Novi: 0822-5679-8857\n\nBiaya, beasiswa, dan prosedur seleksi akan dilengkapi oleh pengelola kampus. Konfirmasikan informasi terbaru kepada panitia sebelum mendaftar.",'link'=>'https://bit.ly/DAFTAR_PMBUKPR2026']);
        $put('pages','kontak','Mari terhubung',['summary'=>'Dapatkan informasi kampus dan penerimaan mahasiswa dari pengelola UKPR.','body'=>"## Lokasi\nPalangka Raya, Kalimantan Tengah.\n\nAlamat jalan, email institusi, jam layanan, dan peta kampus akan dilengkapi oleh pengelola.\n\n## Informasi penerimaan mahasiswa\nHubungi kontak panitia yang tercantum pada [halaman PMB](/pmb)."]);
        $faculties=[['ilmu-sosial-dan-politik','Ilmu Sosial dan Politik','Ilmu Pemerintahan','ilmu-pemerintahan','Pelajari bidang pemerintahan dan perannya dalam masyarakat.'],['teknik','Teknik','Teknik Sipil','teknik-sipil','Jelajahi bidang keteknikan dan pembangunan.'],['perikanan','Perikanan','Budidaya Perairan','budidaya-perairan','Kenali pengembangan bidang budidaya perairan.'],['peternakan','Peternakan','Peternakan','peternakan','Jelajahi ilmu dan pengembangan bidang peternakan.'],['teknologi-komputer','Teknologi Komputer','Rekayasa Sistem Komputer','rekayasa-sistem-komputer','Temukan pilihan studi pada bidang sistem komputer.'],['ekonomi-bisnis','Ekonomi Bisnis','Bisnis Digital','bisnis-digital','Kenali pilihan studi pada bidang bisnis digital.']];
        foreach($faculties as $i=>[$slug,$name,$program,$programSlug,$summary]) {
            $faculty=$put('faculties',$slug,'Fakultas '.$name,['subtitle'=>$program,'summary'=>$summary,'position'=>$i,'body'=>"## Pilihan studi\nProgram studi $program tercantum dalam pengumuman resmi PMB UKPR 2026/2027.\n\nProfil fakultas, dosen, fasilitas, dan informasi akademik akan dilengkapi oleh pengelola."]);
            $put('programs',$programSlug,$program,['parent_id'=>$faculty->id,'subtitle'=>'PROGRAM SARJANA (S1)','summary'=>$summary,'position'=>$i,'body'=>"## Tentang program studi\n$program adalah salah satu pilihan studi Sarjana yang diumumkan UKPR pada PMB 2026/2027.\n\nKurikulum, akreditasi terkini, prospek lulusan, dan rincian biaya akan dilengkapi oleh pengelola kampus.\n\n[Pelajari pendaftaran mahasiswa baru](/pmb)."]);
        }
        $put('leaders','pimpinan-kampus','Pimpinan Universitas',['subtitle'=>'INFORMASI AKAN DILENGKAPI','body'=>'Nama, jabatan, masa tugas, dan foto pimpinan terkini akan dilengkapi pengelola berdasarkan dokumen resmi.']);
        $put('news','mahasiswa-kkn-2026','52 mahasiswa UKPR siap mengabdi',['summary'=>'UKPR melepas 52 peserta KKN sebagai bagian dari pengabdian kepada masyarakat.','published_at'=>'2026-07-20 06:03:23','body'=>"Kuliah Kerja Nyata menjadi bagian pelaksanaan Tri Dharma Perguruan Tinggi. Kegiatan ini membawa mahasiswa UKPR untuk terlibat dalam pengabdian kepada masyarakat.\n\n[Rujukan berita resmi UKPR](https://ukpr.ac.id/berita/8).",'image_path'=>is_file(storage_path('app/private/media/campus.webp'))?'media/campus.webp':null]);
        $put('news','rumah-susun-mahasiswa','Rumah susun mahasiswa UKPR diresmikan',['summary'=>'UKPR mempublikasikan kabar peresmian rumah susun mahasiswa.','published_at'=>'2024-01-10 05:05:59','body'=>"Informasi peresmian rumah susun mahasiswa dipublikasikan UKPR pada Januari 2024.\n\n[Rujukan berita resmi UKPR](https://ukpr.ac.id/berita/7).",'image_path'=>is_file(storage_path('app/private/media/rusun.webp'))?'media/rusun.webp':null]);
        $put('news','kolaborasi-perikanan','Kolaborasi untuk pengelolaan perikanan Kalimantan Tengah',['summary'=>'Fakultas Perikanan UKPR dan SKIPM Palangkaraya menjalin kolaborasi untuk mendukung pengelolaan perikanan.','published_at'=>'2023-11-29 03:40:15','body'=>"Kerja sama mencakup pertukaran narasumber kesehatan ikan, pemanfaatan sarana dan prasarana, serta forum ilmiah bersama.\n\nKolaborasi ini membuka ruang sinergi akademik dan pengelolaan perikanan di Kalimantan Tengah.\n\n[Rujukan berita resmi UKPR](https://ukpr.ac.id/berita/3)."]);
        $put('announcements','pmb-2026-2027','Penerimaan mahasiswa baru 2026/2027',['summary'=>'Informasi jadwal dan persyaratan PMB tersedia untuk calon mahasiswa.','published_at'=>'2026-06-10 05:52:35','body'=>"UKPR membuka penerimaan mahasiswa baru tahun akademik 2026/2027.\n\n[Periksa jadwal, persyaratan, dan kontak panitia](/pmb).",'link'=>'/pmb']);
        $put('facilities','rumah-susun','Rumah susun mahasiswa',['summary'=>'Kenali fasilitas hunian mahasiswa yang diberitakan pada situs resmi UKPR.','body'=>'Rincian kapasitas, persyaratan hunian, biaya, dan layanan akan dilengkapi oleh pengelola kampus.','image_path'=>is_file(storage_path('app/private/media/rusun.webp'))?'media/rusun.webp':null]);
        $album=$put('albums','kegiatan-mahasiswa','Kegiatan mahasiswa',['summary'=>'Dokumentasi kegiatan UKPR dari situs resmi kampus.','image_path'=>is_file(storage_path('app/private/media/campus.webp'))?'media/campus.webp':null]);
        if(is_file(storage_path('app/private/media/campus.webp'))) $put('photos','pelepasan-kkn','Pelepasan mahasiswa KKN',['parent_id'=>$album->id,'image_path'=>'media/campus.webp']);
        $profile=$put('menus','profil','Profil',['position'=>0,'link'=>'/profil']);
        foreach(['sejarah'=>'Sejarah','visi-misi'=>'Visi & misi','pimpinan'=>'Pimpinan'] as $slug=>$label) $put('menus',$slug,$label,['parent_id'=>$profile->id,'link'=>'/'.$slug]);
        $academic=$put('menus','akademik','Akademik',['position'=>1,'link'=>'/fakultas']);
        foreach(['fakultas'=>'Fakultas','prodi'=>'Program studi','fasilitas'=>'Fasilitas'] as $slug=>$label) $put('menus',$slug,$label,['parent_id'=>$academic->id,'link'=>'/'.$slug]);
        $info=$put('menus','informasi','Informasi',['position'=>2,'link'=>'/berita']);
        foreach(['berita'=>'Berita','agenda'=>'Agenda','pengumuman'=>'Pengumuman','galeri'=>'Galeri'] as $slug=>$label) $put('menus',$slug,$label,['parent_id'=>$info->id,'link'=>'/'.$slug]);
        $put('menus','kontak','Kontak',['position'=>3,'link'=>'/kontak']);
        $settings=['site-name'=>'Universitas Kristen Palangka Raya','site-description'=>'Kenali UKPR: pilihan studi Sarjana, kehidupan kampus, serta penerimaan mahasiswa baru di Palangka Raya.','topline'=>'Palangka Raya, Kalimantan Tengah','address'=>'Palangka Raya, Kalimantan Tengah. Alamat lengkap akan dilengkapi.','contact-phone'=>'Kontak PMB tersedia pada halaman Pendaftaran.','footer-text'=>'Ilmu, iman, dan integritas. Bertumbuh bersama, berkontribusi bagi masyarakat.','hero-note'=>'Berakar di Kalimantan. Bertumbuh untuk Indonesia.','hero-photo-label'=>'MAHASISWA UKPR • PENGABDIAN MASYARAKAT','academic-intro'=>'Dari pemerintahan hingga bisnis digital, temukan pilihan studi yang sesuai dengan minatmu.','cta-title'=>'Masa depan dimulai dari pilihanmu.','cta-text'=>'Kenali pilihan studi dan temukan jalanmu bersama UKPR.','sidebar-text'=>'Hubungi pengelola kampus untuk mendapatkan informasi langsung tentang perjalanan studimu.'];
        foreach($settings as $slug=>$value) $put('settings',$slug,ucwords(str_replace('-',' ',$slug)),['body'=>$value]);
        // No accounts, passwords, fabricated schedules or accreditation claims.
    }
}
