@extends('layouts.public')
@section('content')
<section class="um-page-hero"><div class="um-container"><nav class="um-crumbs" aria-label="Breadcrumb"><a href="{{ url('/') }}">Beranda</a><x-icon name="chevron-right"/><span>{{ \App\Models\Content::KINDS[$item->kind] }}</span></nav>@if($item->subtitle)<span class="um-kicker">{{ $item->subtitle }}</span>@endif<h1>{{ $item->title }}</h1>@if($item->summary)<p>{{ $item->summary }}</p>@endif</div></section>
<section class="um-section um-light"><div class="um-container um-detail"><article class="um-article">@if($item->image_path)<img class="um-detail-img" src="{{ route('media',$item) }}" alt="{{ $item->title }}" width="1200" height="800">@endif
@if(in_array($item->kind,['news','announcements']))<p class="um-meta"><x-icon name="calendar"/> Dipublikasikan {{ $item->published_at?->locale('id')->translatedFormat('d F Y') }}@if($item->unit) · <a href="{{ $item->unit->publicUrl() }}">{{ $item->unit->title }}</a>@endif</p>@endif
@if($item->starts_at)<p class="um-event-info"><x-icon name="clock"/> <strong>Waktu:</strong> {{ $item->starts_at->format('d M Y, H:i') }}@if($item->ends_at) – {{ $item->ends_at->format('d M Y, H:i') }}@endif WIB</p>@endif
<div class="prose">{!! Str::markdown($item->body ?? '', ['html_input'=>'strip','allow_unsafe_links'=>false]) !!}</div>
@if($item->link)<a class="um-btn um-btn-yellow" href="{{ $item->link }}" rel="noopener">{{ $item->kind==='pages' && $item->slug==='pmb' ? 'Buka formulir pendaftaran' : 'Informasi selengkapnya' }} <x-icon name="arrow-up-right"/></a>@endif
@if($children->count())<h2 class="um-h3 um-title-bar um-mt">{{ $item->kind==='faculties' ? 'Program studi' : ($item->kind==='albums' ? 'Galeri foto' : 'Informasi terkait') }}</h2><div class="um-grid um-grid-2">@foreach($children as $child)@if($child->kind==='photos')<figure class="um-photo">@if($child->image_path)<a href="{{ route('media',$child) }}"><img src="{{ route('media',$child) }}" alt="{{ $child->title }}" loading="lazy" width="800" height="600"></a>@endif<figcaption><strong>{{ $child->title }}</strong><p>{{ $child->summary }}</p></figcaption></figure>@else @include('public.card',['card'=>$child]) @endif @endforeach</div>@endif
@if(in_array($item->kind,['faculties','programs'],true))<h2 class="um-h3 um-title-bar um-mt">Pengumuman {{ $item->title }}</h2>@forelse($notices as $notice)<a class="um-unit-notice" href="{{ $notice->publicUrl() }}"><span class="um-notice-icon"><x-icon name="megaphone"/></span><div><small>{{ $notice->published_at?->locale('id')->translatedFormat('d M Y') }}@if($notice->unit_id!==$item->id) · {{ $notice->unit?->title }}@endif</small><h3>{{ $notice->title }}</h3>@if($notice->summary)<p>{{ Str::limit($notice->summary,140) }}</p>@endif</div><x-icon name="arrow-up-right"/></a>@empty<p class="um-empty">Belum ada pengumuman untuk {{ $item->title }}.</p>@endforelse @endif
@if($related->count())<h2 class="um-h3 um-title-bar um-mt">Pimpinan kampus</h2><div class="um-grid um-grid-2">@foreach($related as $card)@include('public.card')@endforeach</div>@endif
</article><aside class="um-sidebar"><h2>Kenali Lebih Dekat</h2><a href="{{ url('/fakultas') }}"><x-icon name="building"/> Fakultas & Prodi <x-icon name="chevron-right"/></a><a href="{{ url('/pmb') }}"><x-icon name="graduation-cap"/> Penerimaan Mahasiswa <x-icon name="chevron-right"/></a><a href="{{ url('/fasilitas') }}"><x-icon name="home"/> Fasilitas Kampus <x-icon name="chevron-right"/></a><a href="{{ url('/kontak') }}"><x-icon name="phone"/> Hubungi Kami <x-icon name="chevron-right"/></a><p>{{ $settings['sidebar-text'] ?? 'Dapatkan informasi langsung dari pengelola kampus.' }}</p><a class="um-btn um-btn-yellow um-btn-block" href="{{ url('/pmb') }}">DAFTAR SEKARANG</a></aside></div></section>
@endsection
