document.documentElement.classList.add('js');
const toggle=document.querySelector('.nav-toggle'), navigation=document.querySelector('#navigation');
const closeDrops=except=>document.querySelectorAll('.um-has-drop.is-open').forEach(item=>{if(item!==except){item.classList.remove('is-open');item.querySelector('button')?.setAttribute('aria-expanded','false')}});
if(toggle&&navigation){toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));navigation.style.top=Math.max(0,document.querySelector('.um-header').getBoundingClientRect().bottom)+'px';navigation.classList.toggle('is-open',open)});document.addEventListener('keydown',event=>{if(event.key==='Escape'){toggle.setAttribute('aria-expanded','false');navigation.classList.remove('is-open');closeDrops()}})}
document.querySelectorAll('.um-has-drop>button').forEach(button=>button.addEventListener('click',()=>{const item=button.parentElement,open=!item.classList.contains('is-open');closeDrops(item);item.classList.toggle('is-open',open);button.setAttribute('aria-expanded',String(open))}));
document.addEventListener('click',event=>{if(!event.target.closest('.um-has-drop'))closeDrops()});
const totop=document.querySelector('.um-totop');
if(totop){const onScroll=()=>totop.classList.toggle('is-visible',scrollY>400);addEventListener('scroll',onScroll,{passive:true});onScroll();totop.addEventListener('click',event=>{event.preventDefault();scrollTo({top:0,behavior:'smooth'})})}
const slides=[...document.querySelectorAll('.um-hero-slides img')], dots=[...document.querySelectorAll('.um-hero-dots button')];
if(slides.length>1){let current=0,timer;const show=index=>{slides[current].classList.remove('is-active');dots[current]?.classList.remove('is-active');current=(index+slides.length)%slides.length;slides[current].classList.add('is-active');dots[current]?.classList.add('is-active')};const start=()=>{clearInterval(timer);timer=setInterval(()=>show(current+1),6000)};dots.forEach((dot,index)=>dot.addEventListener('click',()=>{show(index);start()}));start()}
document.querySelectorAll('[data-scroll]').forEach(button=>button.addEventListener('click',()=>{const track=document.getElementById(button.dataset.target),card=track?.firstElementChild;if(card)track.scrollBy({left:Number(button.dataset.scroll)*(card.offsetWidth+24),behavior:'smooth'})}));
const reveal=document.querySelectorAll('[data-reveal]');
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-in');observer.unobserve(entry.target)}}),{threshold:.12});reveal.forEach(el=>observer.observe(el))}else reveal.forEach(el=>el.classList.add('is-in'));
document.querySelectorAll('[data-count]').forEach(el=>{const target=Number(el.dataset.count);if(!target)return;const io=new IntersectionObserver(([entry])=>{if(!entry.isIntersecting)return;io.disconnect();const t0=performance.now();const step=now=>{const p=Math.min((now-t0)/1200,1);el.textContent=Math.round(target*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(step)};requestAnimationFrame(step)});io.observe(el)});
document.querySelectorAll('form[data-confirm]').forEach(form=>form.addEventListener('submit',event=>{if(!window.confirm(form.dataset.confirm))event.preventDefault()}));
const title=document.querySelector('#title'),slug=document.querySelector('#slug');
if(title&&slug&&!slug.value){let touched=false;slug.addEventListener('input',()=>touched=true);title.addEventListener('input',()=>{if(!touched)slug.value=title.value.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,160)})}
const adBurger=document.querySelector('.ad-burger'),adSide=document.querySelector('#ad-side');
if(adBurger&&adSide){const setSide=open=>{adSide.classList.toggle('is-open',open);adBurger.setAttribute('aria-expanded',String(open))};adBurger.addEventListener('click',()=>setSide(!adSide.classList.contains('is-open')));document.querySelector('[data-ad-close]')?.addEventListener('click',()=>setSide(false));document.addEventListener('keydown',event=>{if(event.key==='Escape')setSide(false)})}
const adFile=document.querySelector('.ad-file'),adPreview=document.querySelector('.ad-drop-preview');
if(adFile&&adPreview)adFile.addEventListener('change',()=>{const file=adFile.files[0];if(!file)return;adPreview.src=URL.createObjectURL(file);adPreview.hidden=false});
